name: Build kmod-sched-netem for GL-MT6000 (Flint 2)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk wget python3 unzip subversion git file

      - name: Download OpenWrt SDK 24.10.0 (mediatek/filogic)
        run: |
          wget -q --show-progress https://downloads.openwrt.org/releases/24.10.0/targets/mediatek/filogic/openwrt-sdk-24.10.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz
          tar -xf openwrt-sdk-24.10.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz

      - name: Prepare SDK feeds
        run: |
          cd openwrt-sdk-24.10.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build kmod-sched-netem
        run: |
          cd openwrt-sdk-24.10.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64
          make defconfig
          # try both likely package paths
          make package/kernel/linux/modules/sched-netem/compile V=s || make package/kmod-sched-netem/compile V=s

      - name: Upload ipk artifact
        uses: actions/upload-artifact@v4
        with:
          name: kmod-sched-netem-ipk
          path: openwrt-sdk-24.10.0-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64/bin/packages/**/kmod-sched-netem*.ipk
